
POST http://localhost:3000/register
Content-Type: application/json

{
  "login": "knowak",
  "password": "haslo123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "knowak",
  "password": "haslo123"
}

###

POST http://localhost:3000/add
Content-Type: application/json
Authorization: 0.s6k97i9qcm

{
  "title": "Instagram",
  "password": "haslo123"
}

###

GET http://localhost:3000/passwords
Authorization: 0.4qgf8dwdtkf