POST http://localhost:3000/register
Content-Type: application/json

{
  "login": "admin",
  "password": "1234"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "admin",
  "password": "1234"
}

###

POST http://localhost:3000/add
Content-Type: application/json
Authorization: 0.a72z6z2vm8l

{
  "title": "Instagram",
  "password": "superHaslo234"
}

###

GET http://localhost:3000/passwords
Authorization: 0.a72z6z2vm8l