
POST http://localhost:3000/register
Content-Type: application/json

{
  "login": "admin",
  "password": "abc123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "admin",
  "password": "haslo123"
}

###

POST http://localhost:3000/add
Content-Type: application/json
Authorization: 0.b79f4jssl2d

{
  "title": "Facebook",
  "password": "alla"
}

###

GET http://localhost:3000/passwords
Authorization: 0.jyybuav2k1b

###

DELETE http://localhost:3000/password/1777327231271
Authorization: 0.dm6q2tb4ase

###

PUT http://localhost:3000/password/1777328503224
Content-Type: application/json
Authorization: 0.jyybuav2k1b

{
  "newPassword": "nowehaslo"
}

###

GET http://localhost:3000/search?q=on
Authorization: 0.jyybuav2k1b

###

POST http://localhost:3000/logout
Authorization: 0.b79f4jssl2d